# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IntendCli < Formula
  desc "CLI for intend.do - manage your intentions from the terminal"
  homepage "https://github.com/dsvolk/intend-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.2.0/intend-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "4410358cedb3c57d320233de9156a8d33b911a6a7403bb982750eb668c5714be"

      define_method(:install) do
        bin.install "intend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.2.0/intend-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "35bf03cb84ca54c5a08933cde10c971101fd5b5121e4d8c83043cfef3dea15a4"

      define_method(:install) do
        bin.install "intend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.2.0/intend-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "bdb7fa10441da12a59671bc27fbd902aa24c5172510e9075831bbc082a477a14"
      define_method(:install) do
        bin.install "intend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.2.0/intend-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "50ff7e1fc432214961689da831ee0eec48f0bde93bc442285311fb5646e7fb17"
      define_method(:install) do
        bin.install "intend"
      end
    end
  end

  test do
    system "#{bin}/intend", "--help"
  end
end
