# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IntendCli < Formula
  desc "CLI for intend.do - manage your intentions from the terminal"
  homepage "https://github.com/dsvolk/intend-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.3.1/intend-cli_0.3.1_darwin_amd64.tar.gz"
      sha256 "96be17b93b7dc43a2291bdd34f8fefb5188b5c7105b855b99c4fd16238516d2f"

      define_method(:install) do
        bin.install "intend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.3.1/intend-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "2a5daeda161aa6a6d0d4583ae25b4de1311b2dcb826026df37643342d478f015"

      define_method(:install) do
        bin.install "intend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.3.1/intend-cli_0.3.1_linux_amd64.tar.gz"
      sha256 "a88d2672fb5f0683d8b60c0eab3ff3253a3ba54783eb923170334f0b6b7ce62a"
      define_method(:install) do
        bin.install "intend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.3.1/intend-cli_0.3.1_linux_arm64.tar.gz"
      sha256 "a2863497ddc41a53f4215d73e1ed259aa5915c355b491b313293c308223170ff"
      define_method(:install) do
        bin.install "intend"
      end
    end
  end

  test do
    system "#{bin}/intend", "--help"
  end
end
