# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IntendCli < Formula
  desc "CLI for intend.do - manage your intentions from the terminal"
  homepage "https://github.com/dsvolk/intend-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.2.1/intend-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "f01e3a0460bd3bf840efdf9df97ae67e640b29bff12c4f2de2141203a9dbf01a"

      define_method(:install) do
        bin.install "intend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.2.1/intend-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "bd0dbc408fe3813a32249ebf0aa540131bd296edbb5e592c9f681b5808649570"

      define_method(:install) do
        bin.install "intend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.2.1/intend-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "468125cb8b1e28d301c588cfeafb2e178eb0e5e0bb445b63940952f424b1d925"
      define_method(:install) do
        bin.install "intend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsvolk/intend-cli/releases/download/v0.2.1/intend-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "e0c6ba058a2a9f1f69c3d009ab8266e5c6306fec877258619e8fac9329a67350"
      define_method(:install) do
        bin.install "intend"
      end
    end
  end

  test do
    system "#{bin}/intend", "--help"
  end
end
